### ISSUE TITLE
Add names in indigenous languages of the United States

### ISSUE THREAD

**Issue by 1ec5** [osmus/tileservice#14]
We include a lot of languages in the vector tiles, but many indigenous languages of the United States are missing:

https://github.com/osmus/tileservice/blob/edcdedfe078b5e25560e863b96687e3b72a51bd1/renderer/render_once.sh#L51

Here’s a list I cobbled together of extant [indigenous languages](https://en.wikipedia.org/wiki/Languages_of_the_United_States#List_of_Native_American_languages) and their dialects that are spoken in the U.S., that are spoken by more than 500 people as of 2008, and that have any coverage at all in OSM:

Language | ISO&nbsp;639
----|----
Yupik | [`ypk`](https://taginfo.openstreetmap.org/keys/name:ypk#overview)
O’odham | [`ood`](https://taginfo.openstreetmap.org/keys/name:ood#overview)
Western Apache | [`apw`](https://taginfo.openstreetmap.org/keys/name:apw#overview)
Mescalero-Chiricahua | [`apm`](https://taginfo.openstreetmap.org/keys/name:apm#overview)
Jicarilla | [`apj`](https://taginfo.openstreetmap.org/keys/name:apj#overview)
Eastern Keres | [`kee`](https://taginfo.openstreetmap.org/keys/name:kee#overview)
Western Keres | [`kjq`](https://taginfo.openstreetmap.org/keys/name:kjq#overview)
Zuni | [`zun`](https://taginfo.openstreetmap.org/keys/name:zun#overview)
Ottawa | [`otw`](https://taginfo.openstreetmap.org/keys/name:otw#overview)
Hopi | [`hop`](https://taginfo.openstreetmap.org/keys/name:hop#overview)
Iñupiaq | [`ik`](https://taginfo.openstreetmap.org/keys/name:ik#overview)
Northwest Alaska Iñupiatun | [`esk`](https://taginfo.openstreetmap.org/keys/name:esk#overview)
Tewa | [`tew`](https://taginfo.openstreetmap.org/keys/name:tew#overview)
Chickasaw | [`cic`](https://taginfo.openstreetmap.org/keys/name:cic#overview)
Muscogee | [`mus`](https://taginfo.openstreetmap.org/keys/name:mus#overview)
Alabama | [`akz`](https://taginfo.openstreetmap.org/keys/name:akz#overview)
Koasati | [`cku`](https://taginfo.openstreetmap.org/keys/name:cku#overview)
Crow | [`cro`](https://taginfo.openstreetmap.org/keys/name:cro#overview)
Shoshoni | [`shh`](https://taginfo.openstreetmap.org/keys/name:shh#overview)
Southern Tiwa | [`tix`](https://taginfo.openstreetmap.org/keys/name:tix#overview)
Taos | [`twf`](https://taginfo.openstreetmap.org/keys/name:twf#overview)
Jemez | [`tow`](https://taginfo.openstreetmap.org/keys/name:tow#overview)
Blackfoot | [`bla`](https://taginfo.openstreetmap.org/keys/name:bla#overview)
Umatilla | [`uma`](https://taginfo.openstreetmap.org/keys/name:uma#overview)
Yakima | [`yak`](https://taginfo.openstreetmap.org/keys/name:yak#overview)
Northern Paiute | [`pao`](https://taginfo.openstreetmap.org/keys/name:pao#overview)
Mono | [`mnr`](https://taginfo.openstreetmap.org/keys/name:mnr#overview)
Colorado River Numic | [`ute`](https://taginfo.openstreetmap.org/keys/name:ute#overview)
Ahtna | [`aht`](https://taginfo.openstreetmap.org/keys/name:aht#overview)
Denaʼina | [`tfn`](https://taginfo.openstreetmap.org/keys/name:tfn#overview)
Deg Xinag | [`ing`](https://taginfo.openstreetmap.org/keys/name:ing#overview)
Holikachuk | [`hoi`](https://taginfo.openstreetmap.org/keys/name:hoi#overview)
Koyukon | [`koy`](https://taginfo.openstreetmap.org/keys/name:koy#overview)
Upper Kuskokwim | [`kuu`](https://taginfo.openstreetmap.org/keys/name:kuu#overview)
Tanacross | [`tcb`](https://taginfo.openstreetmap.org/keys/name:tcb#overview)
Upper Tanana | [`tau`](https://taginfo.openstreetmap.org/keys/name:tau#overview)
Gwichʼin | [`gwi`](https://taginfo.openstreetmap.org/keys/name:gwi#overview)
Hän | [`haa`](https://taginfo.openstreetmap.org/keys/name:haa#overview)
Hupa | [`hup`](https://taginfo.openstreetmap.org/keys/name:hup#overview)
Seneca | [`see`](https://taginfo.openstreetmap.org/keys/name:see#overview)
Kiowa | [`kio`](https://taginfo.openstreetmap.org/keys/name:kio#overview)
Aleut | [`ale`](https://taginfo.openstreetmap.org/keys/name:ale#overview)
Salishan | [`sal`](https://taginfo.openstreetmap.org/keys/name:sal#overview)
Lushootseed | [`lut`](https://taginfo.openstreetmap.org/keys/name:lut#overview)
North Straits Salish | [`str`](https://taginfo.openstreetmap.org/keys/name:str#overview)
Cowlitz | [`cow`](https://taginfo.openstreetmap.org/keys/name:cow#overview)
Okanagan | [`oka`](https://taginfo.openstreetmap.org/keys/name:oka#overview)
Flathead | [`fla`](https://taginfo.openstreetmap.org/keys/name:fla#overview)
Fox and Sauk | [`sac`](https://taginfo.openstreetmap.org/keys/name:sac#overview)
Kickapoo | [`kic`](https://taginfo.openstreetmap.org/keys/name:kic#overview)
Arapaho | [`arp`](https://taginfo.openstreetmap.org/keys/name:arp#overview)
Tlingit | [`tli`](https://taginfo.openstreetmap.org/keys/name:tli#overview)
Central Siberian Yupik | [`ess`](https://taginfo.openstreetmap.org/keys/name:ess#overview)
Maliseet-Passamaquoddy | [`pqm`](https://taginfo.openstreetmap.org/keys/name:pqm#overview)
Nez Perce | [`nez`](https://taginfo.openstreetmap.org/keys/name:nez#overview)
Hidatsa | [`hid`](https://taginfo.openstreetmap.org/keys/name:hid#overview)
Karuk | [`kyh`](https://taginfo.openstreetmap.org/keys/name:kyh#overview)
Oneida | [`one`](https://taginfo.openstreetmap.org/keys/name:one#overview)

**Comment by quincylvania** [comment]
@1ec5 Thanks! I'll make a little script to add these in so we don't have to do it by hand.

Do you happen to know how much performance cost there is for supporting a low-coverage language? I'm inclined to support as many as we can, no matter how few speakers, assuming that there's no significant penalty. People will be more likely to add language data if they can see it on a map.

**Comment by quincylvania** [comment]
Here's the script if anyone is interested.

```
let langs = "ab,ace,af,als,am,an,ar,arz,as,ast,az,az-Arab,az-cyr,azb,ba,bar,bat-smg,be,be-tarask,ber,bg,bm,bn,bo,bpy,br,bs,bxr,ca,cdo,ce,ceb,cho,chr,chy,ckb,co,cr,crh,crh-cyr,crk,cs,csb,cv,cy,da,dak,de,dsb,dv,dz,ee,egl,el,en,eo,es,et,eu,fa,fi,fil,fit,fo,fr,frr,full,fur,fy,ga,gag,gan,gcf,gd,gl,gn,gr,grc,gsw,gu,gv,ha,hak,hak-HJ,haw,he,hi,hif,hr,hsb,ht,hu,hur,hy,ia,id,ie,ilo,int,io,is,it,iu,ja,ja_kana,ja_rm,ja-Hira,ja-Latn,jv,ka,kab,kbd,ki,kk,kk-Arab,kl,km,kn,ko,ko-Hani,ko-Latn,krc,krl,ks,ku,kv,kw,ky,la,lb,left,lez,li,lij,lld,lmo,ln,lo,lrc,lt,lv,lzh,md,mdf,mez,mg,mhr,mi,mia,mk,ml,mn,mo,moh,mr,mrj,ms,ms-Arab,mt,mwl,my,myv,mzn,nah,nan,nan-HJ,nan-POJ,nan-TL,nds,ne,nl,nn,no,nov,nv,oc,oj,old,or,os,ota,pa,pam,pcd,pfl,pl,pms,pnb,pot,ps,pt,pt-BR,pt-PT,qu,right,rm,ro,ru,rue,rw,sah,sat,sc,scn,sco,sd,se,sh,si,sju,sk,sl,sma,smj,so,sq,sr,sr-Latn,su,sv,sw,syc,szl,ta,te,TEC,tg,th,th-Latn,ti,tk,tl,tr,tt,tt-lat,udm,ug,uk,ur,uz,uz-Arab,uz-cyr,uz-Cyrl,uz-Latn,vec,vi,vls,vo,wa,war,win,wiy,wo,wuu,xmf,yi,yo,yue,yue-Hant,yue-Latn,za,zgh,zh,zh_pinyin,zh_zhuyin,zh-Hans,zh-Hant,zh-Latn-pinyin,zu,zza";
let langs2 = "ypk,ood,apw,apm,apj,kee,kjq,zun,otw,hop,ik,esk,tew,cic,mus,akz,cku,cro,shh,tix,twf,tow,bla,uma,yak,pao,mnr,ute,aht,tfn,ing,hoi,koy,kuu,tcb,tau,gwi,haa,hup,see,kio,ale,sal,lut,str,cow,oka,fla,sac,kic,arp,tli,ess,pqm,nez,hid,kyh,one"

console.log(langs.split(',').concat(langs2.split(',')).sort(function (a, b) {
    return a.toLowerCase().localeCompare(b.toLowerCase());
}).join(","));
```

**Comment by iandees** [comment]
> Do you happen to know how much performance cost there is for supporting a low-coverage language?

If a tile has no features with the attribute values in a particular language, then it shouldn't get written to the tile at all, so it should be "free" to add as many languages as you want. As soon as one feature in a tile has data for one of these languages, then it gets a few bytes for the attribute name and a few bytes for the value.

It might be a good idea to double-check that the code used to generate the tiles is actually skipping blanks/nulls.

**Comment by 1ec5** [comment]
> It might be a good idea to double-check that the code used to generate the tiles is actually skipping blanks/nulls.

Yes, Planetiler skips unset name fields; this is what makes OSM Americana’s bilingual labeling work. So it should have negligible impact on tile size realistically.

Interestingly, there doesn’t seem to be a very good correspondence between language speakers and number of tagged features for indigenous languages in general. I guess it would be easier to maintain a language list more automatically based on whatever is currently tagged in OSM. But at the same time, invalid language codes should be filtered out, like `TEC` and `left`, which are currently in the list somehow.
