### ISSUE TITLE
Add names in more indigenous languages of Canada

### ISSUE THREAD

**Issue by 1ec5** [osmus/tileservice#20]
As a followup to #14, the tiles should also expose more indigenous languages of Canada. There’s no particular reason that we’ve omitted them so far, other than a lack of demand, but now OSM Canadiana needs these languages: jarek/openstreetmap-canadiana@093b5dbfcd547b98f1f508e8c293e000fc76f01d. Some of these languages are also spoken in the U.S., but even the ones specific to Canada are worth adding to the tiles, since the two mapping communities share a common goal of promoting multilingualism and respect for indigenous cultures.

As of writing, the languages we need to add are:

Language | ISO&nbsp;639
----|----
Algonquin | [`alq`](https://taginfo.openstreetmap.org/keys/name:alq#overview)
Cayuga | [`cay`](https://taginfo.openstreetmap.org/keys/name:cay#overview)
Cree (Latin) | [`cr-Latn`](https://taginfo.openstreetmap.org/keys/name:cr-Latn#overview)
Delaware | [`del`](https://taginfo.openstreetmap.org/keys/name:del#overview)
Gitxsan | [`git`](https://taginfo.openstreetmap.org/keys/name:git)
Inuktitut (Latin) | [`iu-Latn`](https://taginfo.openstreetmap.org/keys/name:iu-Latn)
Mi’kmaq | [`mic`](https://taginfo.openstreetmap.org/keys/name:mic)
Oji-Cree | [`ojs`](https://taginfo.openstreetmap.org/keys/name:ojs)
Onondaga | [`ono`](https://taginfo.openstreetmap.org/keys/name:ono)
Squamish | [`squ`](https://taginfo.openstreetmap.org/keys/name:squ)
Wyandot | [`wya`](https://taginfo.openstreetmap.org/keys/name:wya)

https://github.com/osmus/tileservice/blob/e283dbd794191685b1976f992a29b6599f45f17e/renderer/render_once.sh#L51

/cc @jarek

**Comment by jarek** [comment]
The list above is from my first pass, when I checked for language codes with over 50 uses in Canada.

I did some more work now and here's a full list of languages used in practice in OSM in Canada in `name:<lang>` tags that I filtered to list languages that are indigenous to Canada (or in some cases to U.S. where they're in a neighbouring language family).

Source is Geofabrik's taginfo via JSON: <https://taginfo.geofabrik.de/north-america:canada/api/4/keys/all?include=prevalent_values&sortname=count_all&sortorder=desc&rp=999&page=1&query=name:> plus a quick Python script and manual checking of Wikipedia.

The Geofabrik taginfo for Canada seems to include borders of neighbouring nations (I've seen names for USA, St Pierre and Miquelon, Alaska, Maine, Dakota, etc) and so potentially some of these are only used on non-Canadian data, but you might want or already have the languages used for these American place names so I presume it's not a big problem.

There are altogether 81 valid ISO 639-3 codes (including valid script codes) for Indigenous names in Canada. Another 17 `name:<lang>` keys have values identifiable (to this settler) as Indigenous, but use codes not in ISO 639-3 and could probably be retagged (probably to one of those 81). If you want to limit it, about 46 codes have 10 uses or more, about 34 have 20 uses or more, and about 20 have 50 uses or more.

I don't yet know if we will use all of them, but if they're tagged, I feel they'd be at least nice to have.

CSVs: https://gist.github.com/jarek/4142ac0485ca9e77781e1176b50724d3

**Comment by quincylvania** [comment]
@jarek Thanks for the data. I added all the languages with official ISO codes.

**Comment by 1ec5** [comment]
> in case adding the languages could be a performance issue

Performance shouldn’t be an issue as far as I can tell. Relatively few features have very many name tags. In theory, we could just pull in any `name:*` subkey we find, but curating this list allows us to exclude invalid codes and valid subkeys that aren’t for localized names. As for the Wikidata fallback, apparently Planetiler is already getting all the labels Wikidata has for every referenced item and filtering after the fact, so there’s no additional resource usage there either.
